<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="/css/styles.css" rel="stylesheet">
    <title>Slim Task Manager</title>
</head>

<body>

<header>

</header>

<main>

    <h2>Tasks</h2>

    <?php

    foreach($tasks as $task) {
        echo '<div class="task">';
        echo '<p>' . $task['title'] . '</p>';
        echo '<p>' . $task['description'] . '</p>';
        echo '<p>' . $task['due_date'] . '</p>';
        echo '<p>' . $task['status'] . '</p>';
        echo '<p>' . $task['created_at'] . '</p>';
        echo '<p>' . $task['updated_at'] . '</p>';
        echo '</div>';
    }

    ?>

</main>

<footer>

</footer>

</body>

</html>