<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
          integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <title>Slim Task Manager</title>
    <link rel="stylesheet" href="../css/styles.css"/>
</head>

<body>

<main>

    <h1>Home</h1>

    <table>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Due Date</th>
            <th>Status</th>
            <th>Created</th>
            <th>Updated</th>
            <th></th>
        </tr>
        <?php
        foreach ($tasks as $task) {
            $created_at = new DateTime($task['created_at']);
            $updated_at = new DateTime($task['updated_at']);
            echo '<tr>';
            echo '<td>' . $task['title'] . '</td>';
            echo '<td>' . $task['description'] . '</td>';
            echo '<td>' . $task['due_date'] . '</td>';
            echo '<td>' . $task['status'] . '</td>';
            echo '<td>' . $created_at->format('d/m/y H:i') . '</td>';
            echo '<td>' . $updated_at->format('d/m/y H:i') . '</td>';

            $taskId = $task['id'];

            echo '<td class="button-cell">';
            echo '<form method="post" action ="/tasks/' . $taskId . '">';
            echo '<input type="hidden" name="_method" value="DELETE">';
            echo '<button type="submit">Delete</button>';
            echo '</form>';

            echo '<button type="button" onclick="document.getElementById(\'editDialog_' . $taskId . '\').showModal()">Edit</button>';
            echo '<button>✓</button>';

            echo '<dialog id="editDialog_' . $taskId .'">';
            echo '<h2>Edit Task</h2>';
            echo '<form method="post" action ="/editTask/' . $taskId . '">';
            echo '<label for="title_' . $taskId . '">Title</label>';
            echo '<input type="text" name="title" id="title_' . $taskId . '" value="' . $task['title'] . '">';
            echo '<label for="description_' . $taskId . '">Description</label>';
            echo '<input type="text" name="description" id="description_' . $taskId . '" value="' . $task['description'] . '">';
            echo '<label for="due_date_' . $taskId . '">Date due</label>';
            echo '<input type="text" name="due_date" id="due_date_' . $taskId . '" value="' . $task['due_date'] . '">';
            echo '<button type="submit">Save</button>';
            echo '</form>';
            echo '<form method="dialog">';
            echo '<button>Close</button>';
            echo '</form>';
            echo '</dialog>';
            echo '</td>';
            echo '</tr>';
        }

        ?>
    </table>

    <form method="post">
        <label for="title">Title</label>
        <input name="title" id="title" type="text" autofocus/>
        <label for="description">Description</label>
        <input name="description" id="description" type="text"/>
        <input type="submit">
    </form>

</main>

</body>

</html>